# Generated by Django 4.0.2 on 2022-05-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
